name: Create Packages

on:
  release:
    types: [created]

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          devscripts \
          debhelper \
          dh-make \
          lintian

    - name: Create DEB package
      run: |
        mkdir -p pkg/debian
        cp -r * pkg/
        cd pkg
        dh_make --createorig -s -y
        dpkg-buildpackage -us -uc
        lintian ../*.deb

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deb-package
        path: ../*.deb